/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebarStart: [
    {type: 'autogenerated', dirName: 'start'},
  ],
  sidebarLearn: [
    'learn/getting-started',
    {
      type: 'category',
      label: 'Module 1 - Blockchain Fundamental Concepts',
      collapsed: true,
      items: [
        'learn/module-1/basic-cryptography',
        'learn/module-1/what-is-a-blockchain',
        'learn/module-1/system-of-coordination',
        'learn/module-1/network-participants',
        'learn/module-1/trustless-computing',
        'learn/module-1/data-ownership',
        'learn/module-1/privacy',
        'learn/module-1/censorship-resistance',
        'learn/module-1/money-as-the-first-app',
        {type: 'link', label: '🔥 Fireside Chat', href: 'https://docs.google.com/presentation/d/1iF2iVo_g5daJAvgf1kP14TEzw9MXsO2ZJPHfHN80qNw/'},
      ],
    },
    {
      type: 'category',
      label: 'Module 2 - Blockchain Technical Concepts',
      collapsed: true,
      items: [
        'learn/module-2/block-production',
        'learn/module-2/consensus-mechanisms',
        'learn/module-2/security',
        'learn/module-2/keys-and-addresses',
        'learn/module-2/transactions',
        'learn/module-2/gas',
        'learn/module-2/block-explorers',
        'learn/module-2/oracles',
        'learn/module-2/miner-extractable-value',
        'learn/module-2/scalability-trilemma',
        'learn/module-2/layer-2s-and-sidechains',
        {type: 'link', label: '🔥 Fireside Chat', href: 'https://docs.google.com/presentation/d/1iF2iVo_g5daJAvgf1kP14TEzw9MXsO2ZJPHfHN80qNw/'},
      ],
    },
    {
      type: 'category',
      label: 'Module 3 - Blockchain Wars',
      collapsed: true,
      items: [
        'learn/module-3/bitcoin',
        'learn/module-3/zcash',
        'learn/module-3/monero',
        'learn/module-3/ethereum',
        'learn/module-3/bnbchain',
        'learn/module-3/solana',
        'learn/module-3/polkadot',
        'learn/module-3/cosmos',
        'learn/module-3/near',
        'learn/module-3/avalanche',
        'learn/module-3/fantom',
        'learn/module-3/other-blockchains',
        'learn/module-3/bridging',
        {type: 'link', label: '🔥 Fireside Chat', href: 'https://docs.google.com/presentation/d/1iF2iVo_g5daJAvgf1kP14TEzw9MXsO2ZJPHfHN80qNw/'},
      ],
    },
    {
      type: 'category',
      label: 'Module 4 - Financial Systems',
      collapsed: true,
      items: [
        'learn/module-4/traditional-centralized-finance',
        'learn/module-4/trading-jargon',
        'learn/module-4/tokens-and-programmable-assets',
        'learn/module-4/automated-market-makers',
        'learn/module-4/money-markets',
        'learn/module-4/liquidity-provision',
        'learn/module-4/stablecoins',
        'learn/module-4/decentralized-finance',
        {type: 'link', label: '🔥 Fireside Chat', href: 'https://docs.google.com/presentation/d/1iF2iVo_g5daJAvgf1kP14TEzw9MXsO2ZJPHfHN80qNw/'},
      ],
    },
    {
      type: 'category',
      label: 'Module 5 - Development',
      collapsed: true,
      items: [
        'learn/module-5/code-is-law',
        'learn/module-5/evm-and-smart-contracts',
        'learn/module-5/solidity',
        'learn/module-5/frameworks-and-tools',
        'learn/module-5/subgraphs',
        'learn/module-5/architecture-and-software-stack',
        {type: 'link', label: '🔥 Fireside Chat', href: 'https://docs.google.com/presentation/d/1iF2iVo_g5daJAvgf1kP14TEzw9MXsO2ZJPHfHN80qNw/'},
      ],
    },
    {
      type: 'category',
      label: 'Module 6 - Cryptoeconomics and Game Theory',
      collapsed: true,
      items: [
        'learn/module-6/tokenomics',
        'learn/module-6/incentive-and-yield-mechanisms',
        'learn/module-6/bribes-and-cooperation-mechanisms',
        {type: 'link', label: '🔥 Fireside Chat', href: 'https://docs.google.com/presentation/d/1iF2iVo_g5daJAvgf1kP14TEzw9MXsO2ZJPHfHN80qNw/'},
      ],
    },
    {
      type: 'category',
      label: 'Module 7 - Product Design',
      collapsed: true,
      items: [
        'learn/module-7/web2-vs-web3',
        'learn/module-7/decentralized-applications',
        'learn/module-7/governance',
        'learn/module-7/wallets',
        'learn/module-7/ux-patterns',
        {type: 'link', label: '🔥 Fireside Chat', href: 'https://docs.google.com/presentation/d/1iF2iVo_g5daJAvgf1kP14TEzw9MXsO2ZJPHfHN80qNw/'},
      ],
    },
    {
      type: 'category',
      label: 'Module 8 - Crypto Subculture and Tribes',
      collapsed: true,
      items: [
        'learn/module-8/crypto-twitter',
        'learn/module-8/influencers-and-thought-leaders',
        'learn/module-8/communication-tools',
        'learn/module-8/good-bad-crypto-subculture',
        {type: 'link', label: '🔥 Fireside Chat', href: 'https://docs.google.com/presentation/d/1iF2iVo_g5daJAvgf1kP14TEzw9MXsO2ZJPHfHN80qNw/'},
      ],
    },
  ],
  sidebarBuidl: [
    {type: 'autogenerated', dirName: 'buidl'},
  ],
  sidebarExplore: [
    {type: 'autogenerated', dirName: 'explore'},
  ],
  sidebarResources: [
    {type: 'autogenerated', dirName: 'resources'},
  ],
};
